name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
    - main
    paths:
    - apps/backend/**
    
jobs:
    deploy:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: Install dependencies
          run: npm install
        - name: build
          run: npm run build:backend
        - name: Install Vercel CLI
          run: npm install --global vercel@latest
        - name: Deploy Project Artifacts to Vercel
          run: cd apps/backend && vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          
