name: Web - Deploy Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB }}

on:
  workflow_dispatch:
    
  push:
    branches:
    - main
    paths:
    - apps/web/**
    
jobs:
    Linting-And-Testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm install
        - name: Run lint
          run: npm run lint:backend
        - name: Run test
          run: npm run test:backend
          
    Deploy-Production:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install Vercel CLI
          run: npm install --global vercel@latest
        - name: Pull Vercel Environment Information
          run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        - name: Build Project Artifacts
          run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        - name: Deploy Project Artifacts to Vercel
          run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          
